::@echo off
:: > Setup required Environment
:: -------------------------------------
set COMPILER_DIR=C:\raylib\mingw\bin
set PATH=%PATH%;%COMPILER_DIR%
cd %~dp0
:: .
:: > Generating project
:: --------------------------
cmd /c mingw32-make ^
PROJECT_PATH=. ^
PROJECT_NAME=rpb ^
PROJECT_VERSION=1.0 ^
PROJECT_DESCRIPTION="A simple and easy-to-use raylib projects creator^
PROJECT_INTERNAL_NAME=rpc ^
PROJECT_BUILD_PATH=ONE ^
PROJECT_PLATFORM=PLATFORM_DESKTOP ^
PROJECT_CFLAGS="-DSUPPORT_DIRECTORY_SCAN" ^
PROJECT_SRC_FILES="rpc.c external\tinyfiledialogs.c" ^
BUILD_MODE="RELEASE" ^
BUILD_WEB_ASYNCIFY=FALSE ^
BUILD_WEB_MIN_SHELL=TRUE ^
BUILD_WEB_HEAP_SIZE=268435456 ^
RAYLIB_MODULE_AUDIO=FALSE ^
RAYLIB_MODULE_MODELS=FALSE ^
RAYLIB_EXTERNAL_CONFIG_FLAGS=^
"-DEXTERNAL_CONFIG_FLAGS ^
-DSUPPORT_STANDARD_FILEIO ^
-DSUPPORT_GESTURES_SYSTEM ^
-DSUPPORT_MOUSE_GESTURES ^
-DSUPPORT_EVENTS_WAITING ^
-DSUPPORT_COMPRESSION_API ^
-DSUPPORT_QUADS_DRAW_MODE ^
-DSUPPORT_DEFAULT_FONT ^
-DSUPPORT_FILEFORMAT_PNG ^
-DSUPPORT_FILEFORMAT_BMP ^
-DSUPPORT_FILEFORMAT_TGA ^
-DSUPPORT_FILEFORMAT_JPG ^
-DSUPPORT_FILEFORMAT_GIF ^
-DSUPPORT_FILEFORMAT_PSD ^
-DSUPPORT_FILEFORMAT_DDS ^
-DSUPPORT_FILEFORMAT_HDR ^
-DSUPPORT_FILEFORMAT_QOI ^
-DSUPPORT_FILEFORMAT_KTX ^
-DSUPPORT_FILEFORMAT_ASTC ^
-DSUPPORT_FILEFORMAT_PKM ^
-DSUPPORT_FILEFORMAT_PVR ^
-DSUPPORT_FILEFORMAT_TTF ^
-DSUPPORT_IMAGE_EXPORT ^
-DSUPPORT_IMAGE_MANIPULATION ^
-DSUPPORT_IMAGE_GENERATION ^
-DSUPPORT_TEXT_MANIPULATION ^
-DSUPPORT_TRACELOG"
